@startuml


package "Consumer Application CA1" {
    entity "Consumer" as C1
}

package "Consumer Application CA2" {
    entity "Consumer" as C2
}

package "Cluster of Nodes" {
    node "Node 1" {
        frame "Kafka Topic: Topic1 - (2) Rebalancing triggered"  as K1 {
            entity "Partition 1" as P1
            entity "Partition 2" as P2
        }
    }

    node "Node 2" {
            frame "Kafka Topic: Topic2" {
                entity "Partition 1"
        }
    }

    node "Node 3" {
            frame "Kafka Topic: Topic2" {
                entity "Partition 1"
        }
    }
}


K1 <-- C2 : (1) Request for joining the Consumer Group
P1 <-- C1 : (3) Heartbeat signal returns a rebalance signal


@enduml
