@startuml

package "Cluster of Nodes" {
    node "Node 1" {
        frame "Kafka Topic: Topic1\n The Group Coordinator waits for all consumers to send their "JoinGroup" requests. \nIt then assigns partitions based on the chosen assignment strategy.\nOnce partitions are assigned, it sends the new assignments \n back to the consumers in the response to the "SyncGroup" request."  as K1 {
            entity "Partition 1" as P1
            entity "Partition 2" as P2
        }
    }

    node "Node 2" {
            frame "Kafka Topic: Topic2" {
                entity "Partition 1"
        }
    }

    node "Node 3" {
            frame "Kafka Topic: Topic2" {
                entity "Partition 1"
        }
    }
}


package "Consumer Application CA1" {
    entity "Consumer" as C1
}

package "Consumer Application CA2" {
    entity "Consumer" as C2
}

K1 <-- C1: Send a "JoinGroup" request to the Group Coordinator, consumers send a "SyncGroup" request to confirm their participation
K1 <-- C2: Send a "JoinGroup" request to the Group Coordinator, consumers send a "SyncGroup" request to confirm their participation

@enduml
